import "@/styles/globals.css";

import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import { Provider } from "@/providers";
import { anton, inter } from "@/styles/fonts";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.variable} ${anton.variable}`}>
				<Provider>
					<NextTopLoader color="#DC2727" />
					<Header />
					<main className="flex-1 container py-16">{children}</main>
					<Footer />

					<Toaster />
				</Provider>
			</body>
		</html>
	);
}
